package com.cheese.ssh.beans;
// Generated 2016-5-29 18:51:25 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "dhucheese")
public class Order implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer taskId;
	private Integer status;
	private String mesg;
	private String attachment;
	private Date recDate;

	public Order() {
	}

	public Order(Integer userId, Integer taskId, Integer status, String mesg, String attachment, Date recDate) {
		this.userId = userId;
		this.taskId = taskId;
		this.status = status;
		this.mesg = mesg;
		this.attachment = attachment;
		this.recDate = recDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "taskId")
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "mesg")
	public String getMesg() {
		return this.mesg;
	}

	public void setMesg(String mesg) {
		this.mesg = mesg;
	}

	@Column(name = "attachment")
	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recDate", length = 19)
	public Date getRecDate() {
		return this.recDate;
	}

	public void setRecDate(Date recDate) {
		this.recDate = recDate;
	}

}
