package com.cheese.ssh.beans;
// Generated 2016-4-14 22:03:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "dhucheese")
public class User implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private String realname;
	private Integer gender;
	private Date birthday;
	private String phone;
	private String mail;
	private String school;
	private String major;
	private String address;
	private String hometown;
	private String company;
	private String imageaddr;
	private Integer usertype;

	public User() {
	}

	public User(int id) {
		this.id = id;
	}

	public User(int id, String username, String password, String realname, Integer gender, Date birthday, String phone,
			String mail, String school, String major, String address, String hometown, String company, String imageaddr,
			Integer usertype) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.realname = realname;
		this.gender = gender;
		this.birthday = birthday;
		this.phone = phone;
		this.mail = mail;
		this.school = school;
		this.major = major;
		this.address = address;
		this.hometown = hometown;
		this.company = company;
		this.imageaddr = imageaddr;
		this.usertype = usertype;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "realname")
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "mail")
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "school")
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "major")
	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "hometown")
	public String getHometown() {
		return this.hometown;
	}

	public void setHometown(String hometown) {
		this.hometown = hometown;
	}

	@Column(name = "company")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "imageaddr")
	public String getImageaddr() {
		return this.imageaddr;
	}

	public void setImageaddr(String imageaddr) {
		this.imageaddr = imageaddr;
	}

	@Column(name = "usertype")
	public Integer getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Integer usertype) {
		this.usertype = usertype;
	}

}
